## Packages

In [63]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mticks
import matplotlib.dates as mdates
import os
import itertools
import statsmodels.tsa.api as tsa
from pmdarima.model_selection import train_test_split
from pmdarima.arima.utils import ndiffs
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
import warnings

# Data

In [14]:
loan_data = pd.read_csv('/Users/marcolaureano2/Documents/GitHub/kaggle-loan-prediction/credit_risk_dataset.csv')

In [15]:
loan_data

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
1            EDUCATION          B       1000          11.14            0   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
...                ...        ...        ...            ...          ...   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
0                               3  
1                               2  
2                               3  
3                               2  
4                               4  
...                           ...  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30  

[32581 rows x 12 columns]

In [11]:
loan_data.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [12]:
loan_data.tail()

person_age  person_income person_home_ownership  person_emp_length  \
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30

In [13]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  32581 non-null  int64  
 1   person_income               32581 non-null  int64  
 2   person_home_ownership       32581 non-null  object 
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object 
 5   loan_grade                  32581 non-null  object 
 6   loan_amnt                   32581 non-null  int64  
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64  
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object 
 11  cb_person_cred_hist_length  32581 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB


## Inspect Columns

### person_age

In [21]:
loan_data['person_age'].unique()

array([ 22,  21,  25,  23,  24,  26, 144, 123,  20,  32,  34,  29,  33,
        28,  35,  31,  27,  30,  36,  40,  50,  45,  37,  39,  44,  43,
        41,  46,  38,  47,  42,  48,  49,  58,  65,  51,  53,  66,  61,
        54,  57,  59,  62,  60,  55,  52,  64,  70,  78,  69,  56,  73,
        63,  94,  80,  84,  76,  67])

### person_income

In [59]:
loan_data['person_income'].unique()

array([  59000,    9600,   65500, ...,  720000, 1900000,    4888])

In [61]:
loan_data['person_income'].min()

4000

In [62]:
loan_data['person_income'].max()

6000000

### person_emp_length

In [45]:
loan_data['person_income'].unique()

array([  59000,    9600,   65500, ...,  720000, 1900000,    4888])

### person_home_ownership 

In [36]:
loan_data['person_home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER'], dtype=object)

### loan_intent

In [38]:
loan_data['loan_intent'].unique()

array(['PERSONAL', 'EDUCATION', 'MEDICAL', 'VENTURE', 'HOMEIMPROVEMENT',
       'DEBTCONSOLIDATION'], dtype=object)

### loan_grade

In [42]:
loan_data['loan_grade'].unique()

array(['D', 'B', 'C', 'A', 'E', 'F', 'G'], dtype=object)

### loan_amnt

In [43]:
loan_data['loan_amnt'].unique()

array([35000,  1000,  5500,  2500,  1600,  4500, 30000,  1750, 34800,
       34000,  1500, 33950, 33000,  4575,  1400, 32500,  4000,  2000,
       32000, 31050, 24250,  7800, 20000, 10000, 25000, 18000, 12000,
       29100, 28000,  9600,  3000,  6100,  4200,  4750,  4800,  2700,
       27600,  3250, 27500, 27050, 27000, 26000, 25600, 25475, 21600,
       11900, 25300,  3650,  6000,  2400,  3600,  7500,  4950, 21000,
       16000, 22000,  7750, 24000, 15000, 15500,  9000, 23050,  5375,
        6250,  5000,  2100, 14000,  6200,  9950,  4475,  2600,  8000,
        4600,  3500,  7200,  8800,  3175,  2800, 13000,  1800,  3300,
        3200,  2275,  5600,  3625,  4375, 24750, 24500,  3900, 13750,
       15250, 24150,  2250,  4975,  4900, 23975, 23750, 23600, 23575,
        5400,  3375, 23400, 23000,  1200, 22750, 22500, 22400, 22250,
        7400, 21700,  7000, 21500, 21450, 21250,  9250, 20900, 20500,
       20400, 20375, 20050,  6400,  5650, 16600,  7125,  3550,  1275,
        3800,  1625,

### loan_int_rate

In [47]:
loan_data['loan_int_rate'].unique()

array([16.02, 11.14, 12.87, 15.23, 14.27,  7.14, 12.42, 11.11,  8.9 ,
       14.74, 10.37,  8.63,  7.9 , 18.39, 10.65, 20.25, 18.25, 10.99,
        7.49, 16.77, 17.58,  7.29, 14.54, 12.68, 17.74,  9.32,  9.99,
       12.84, 11.12,  6.62, 14.17, 13.85, 13.49,  7.51, 16.89,   nan,
       17.99, 12.69,  7.88, 19.41, 10.38, 15.33, 16.45, 18.62, 15.96,
       11.48,  5.99, 11.58, 15.7 , 15.99, 14.84, 14.42,  6.99, 13.61,
        9.91, 13.48, 12.98, 13.57, 15.68, 13.06, 15.62, 11.71,  8.88,
       12.18, 13.99,  5.42, 12.73, 11.49, 19.91, 11.83, 14.59,  9.64,
       16.35, 18.67, 10.08, 10.36, 12.23, 16.07, 14.22, 14.79, 13.22,
       11.86, 13.43, 15.28, 17.93,  9.25, 10.62, 18.43, 11.36, 15.65,
       13.04, 17.04, 14.83, 14.65, 16.82, 10.25, 14.96, 11.99,  8.49,
        6.17, 16.32, 14.35, 15.21, 14.09, 17.49, 13.92, 16.49,  5.79,
       13.11,  6.54, 12.53, 15.95, 10.74, 15.27, 14.72, 13.35,  7.68,
       14.46, 13.47,  6.03, 12.92, 18.64, 16.7 , 18.3 ,  9.63, 14.7 ,
       15.37, 14.26,

### loan_status 

In [49]:
loan_data['loan_status'].unique()

array([1, 0])

### loan_percent_income

In [50]:
loan_data['loan_percent_income'].unique()

array([0.59, 0.1 , 0.57, 0.53, 0.55, 0.25, 0.45, 0.44, 0.42, 0.16, 0.41,
       0.37, 0.32, 0.3 , 0.06, 0.29, 0.31, 0.22, 0.52, 0.14, 0.49, 0.13,
       0.5 , 0.35, 0.17, 0.27, 0.33, 0.08, 0.03, 0.21, 0.63, 0.47, 0.4 ,
       0.07, 0.38, 0.34, 0.04, 0.23, 0.15, 0.11, 0.43, 0.51, 0.02, 0.28,
       0.26, 0.19, 0.39, 0.09, 0.05, 0.61, 0.18, 0.6 , 0.01, 0.48, 0.12,
       0.54, 0.56, 0.46, 0.36, 0.24, 0.2 , 0.72, 0.64, 0.69, 0.77, 0.83,
       0.65, 0.67, 0.58, 0.71, 0.68, 0.7 , 0.66, 0.  , 0.76, 0.62, 0.78])

### cb_person_default_on_file 

In [52]:
loan_data['cb_person_default_on_file'].unique()

array(['Y', 'N'], dtype=object)

### cb_person_cred_hist_length

In [53]:
loan_data['cb_person_cred_hist_length'].unique()

array([ 3,  2,  4,  8,  7,  6,  9, 10,  5, 11, 16, 15, 12, 13, 17, 14, 25,
       28, 27, 22, 19, 29, 23, 26, 20, 21, 30, 24, 18])

## EDA

In [67]:
loan_data.groupby(['loan_status']).count()

person_age  person_income  person_home_ownership  \
loan_status                                                     
0                 25473          25473                  25473   
1                  7108           7108                   7108   

             person_emp_length  loan_intent  loan_grade  loan_amnt  \
loan_status                                                          
0                        24860        25473       25473      25473   
1                         6826         7108        7108       7108   

             loan_int_rate  loan_percent_income  cb_person_default_on_file  \
loan_status                                                                  
0                    23001                25473                      25473   
1                     6464                 7108                       7108   

             cb_person_cred_hist_length  
loan_status                              
0                                 25473  
1                                  7108

In [80]:
status_1 = loan_data.loc[loan_data['loan_status'] > 0]
status_1

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
5              21           9900                   OWN                2.0   
...           ...            ...                   ...                ...   
32563          52          71520                  RENT                0.0   
32565          57          40000                  RENT                1.0   
32571          60          45600                  RENT                1.0   
32574          52          65004                  RENT                4.0   
32578          65          76000                  RENT                3.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
5              VENTURE          A       2500           7.14            1   
...                ...        ...        ...            ...          ...   
32563        EDUCATION          E       7000          16.82            1   
32565          MEDICAL          A      15000           8.90            1   
32571          VENTURE          B      20000          10.00            1   
32574         PERSONAL          D      20000          15.58            1   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
5                     0.25                         N   
...                    ...                       ...   
32563                 0.10                         Y   
32565                 0.38                         N   
32571                 0.44                         N   
32574                 0.31                         Y   
32578                 0.46                         N   

       cb_person_cred_hist_length  
0                               3  
2                               3  
3                               2  
4                               4  
5                               2  
...                           ...  
32563                          24  
32565                          21  
32571                          26  
32574                          19  
32578                          28  

[7108 rows x 12 columns]

In [81]:
status_0 = loan_data.loc[loan_data['loan_status'] < 1]
status_0

person_age  person_income person_home_ownership  person_emp_length  \
1              21           9600                   OWN                5.0   
14             23         115000                  RENT                2.0   
15             23         500000              MORTGAGE                7.0   
16             23         120000                  RENT                0.0   
20             25         162500                  RENT                2.0   
...           ...            ...                   ...                ...   
32575          52          64500                  RENT                0.0   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

             loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
1              EDUCATION          B       1000          11.14            0   
14             EDUCATION          A      35000           7.90            0   
15     DEBTCONSOLIDATION          B      30000          10.65            0   
16             EDUCATION          A      35000           7.90            0   
20               VENTURE          A      35000           7.49            0   
...                  ...        ...        ...            ...          ...   
32575          EDUCATION          B       5000          11.26            0   
32576           PERSONAL          C       5800          13.16            0   
32577           PERSONAL          A      17625           7.49            0   
32579           PERSONAL          B      15000          11.48            0   
32580            MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
1                     0.10                         N   
14                    0.30                         N   
15                    0.06                         N   
16                    0.29                         N   
20                    0.22                         N   
...                    ...                       ...   
32575                 0.08                         N   
32576                 0.11                         N   
32577                 0.15                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
1                               2  
14                              4  
15                              3  
16                              4  
20                              4  
...                           ...  
32575                          20  
32576                          30  
32577                          19  
32579                          26  
32580                          30  

[25473 rows x 12 columns]

In [85]:
status_1['loan_grade']

0        D
2        C
3        C
4        C
5        A
        ..
32563    E
32565    A
32571    B
32574    D
32578    B
Name: loan_grade, Length: 7108, dtype: object

In [84]:
status_0['loan_grade']

1        B
14       A
15       B
16       A
20       A
        ..
32575    B
32576    C
32577    A
32579    B
32580    B
Name: loan_grade, Length: 25473, dtype: object